/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Push notification handler
self.addEventListener('push', (event) => {
  if (!event.data) return;

  let payload: { title: string; body: string; data?: Record<string, unknown> };
  try {
    payload = event.data.json();
  } catch {
    payload = { title: 'AlGreen MES', body: event.data.text() };
  }

  event.waitUntil(
    self.registration.showNotification(payload.title, {
      body: payload.body,
      icon: '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      data: payload.data,
      tag: payload.data?.type as string | undefined,
    } as NotificationOptions),
  );
});

// Click handler — focus or open the app
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const data = event.notification.data as Record<string, unknown> | undefined;
  let url = '/queue';

  if (data?.type === 'OrderActivated') {
    url = '/queue';
  } else if (data?.type === 'ProcessBlocked') {
    url = '/queue';
  } else if (data?.type === 'DeadlineWarning') {
    url = '/queue';
  }

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
      for (const client of clients) {
        if (new URL(client.url).pathname.startsWith('/') && 'focus' in client) {
          client.navigate(url);
          return client.focus();
        }
      }
      return self.clients.openWindow(url);
    }),
  );
});
